# Generated by Django 5.2.8 on 2026-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequests',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
