# Generated by Django 5.2.8 on 2026-04-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0003_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
