# Generated by Django 5.2.8 on 2026-05-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0003_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_reviews', to='realEstate.userprofile'),
        ),
    ]
