# Generated by Django 5.2.8 on 2026-04-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0006_visitrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitRequest',
            new_name='VisitRequests',
        ),
    ]
