# Generated by Django 5.2.8 on 2026-04-28 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0007_rename_visitrequest_visitrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_agent',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visitrequests',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='realEstate.property'),
        ),
        migrations.AlterField(
            model_name='visitrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='visitrequests',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed'), _negated=True), fields=('user', 'property'), name='unique_active_visit_per_user_property'),
        ),
    ]
