# Generated by Django 5.2.8 on 2026-04-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0008_remove_userprofile_is_agent_userprofile_role_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='visitrequests',
            name='unique_active_visit_per_user_property',
        ),
    ]
