# Generated by Django 5.2.8 on 2026-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0009_remove_visitrequests_unique_active_visit_per_user_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
