# Generated by Django 5.2.8 on 2026-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0011_remove_visitrequests_time_visitrequests_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
